fix: passing artifacts between jobs

diff --git a/.github/workflows/selenium-tests.yml b/.github/workflows/selenium-tests.yml
--- a/.github/workflows/selenium-tests.yml
+++ b/.github/workflows/selenium-tests.yml
@@ -13,6 +13,23 @@ on:
           - edge
 
 jobs:
+  download-artifacts:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+    - name: Download element selectors
+      continue-on-error: true
+      uses: actions/download-artifact@v4
+      with:
+        name: element-selectors
+        path: src/test/resources/
+    - name: Verify downloaded artifact
+      continue-on-error: true
+      run: |
+        ls -l src/test/resources/
+        cat src/test/resources/elementSelectors.properties || echo "File not found"
+
   test:
     runs-on: ubuntu-latest
 
@@ -30,19 +47,6 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
-
-    - name: Download element selectors
-      continue-on-error: true
-      uses: actions/download-artifact@v4
-      with:
-        name: element-selectors
-        path: src/test/resources/
-
-    - name: Verify downloaded artifact
-      continue-on-error: true
-      run: |
-        ls -l src/test/resources/
-        cat src/test/resources/elementSelectors.properties || echo "File not found"
 
     - name: Run build including the test
       env:
